threads: 14

aligner:
  tool: "kallisto"
  # add full paths here
  index_hisat2: "/mnt/d/omar_wsl/rnaseq_pipeline/ref/genome/hisat2_index/grch38/genome"
  index_kallisto: "/mnt/d/omar_wsl/rnaseq_pipeline/ref/genome/kallisto_index/transcriptome.idx"